name: 🐞 Bug Report
description: Report a problem to track and fix it.
title: "[BUG] "
labels: ["type: bug", "status: needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for creating a bug report. Please provide as much detail as possible.

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Which part of the system is affected by this bug?
      options:
        - Backend
        - Frontend
        - Generation Engine
        - Microservice
        - Infrastructure
        - Database
        - Authentication
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Detail the exact steps to reproduce the bug.
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs or Screenshots
      description: Please copy and paste any relevant log output or add screenshots. This is crucial for debugging.
      render: shell