name: Feature or Enhancement
description: Propose a new feature or an improvement to an existing one.
title: "[FEAT] "
labels: ["status: needs-triage"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Type of Request
      description: Is this a brand new feature or an improvement to something that already exists?
      options:
        - Feature
        - Enhancement
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: Is your request related to a problem?
      description: A clear and concise description of what the problem is. Ex. "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Primary Area
      description: Which part of the system would this feature primarily affect?
      options:
        - Backend
        - Frontend
        - Generation Engine
        - Microservice
        - Infrastructure
        - Repository
        - Database
        - Authentication
    validations:
      required: true