name: Technical Task
description: For refactoring, chores, research, or documentation.
title: "[TASK] "
labels: ["status: needs-triage"]
body:
  - type: dropdown
    id: task-type
    attributes:
      label: Type of Task
      description: Select the category that best describes this task.
      options:
        - Tech Debt
        - Chore
        - Research
        - Documentation
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Primary Area
      description: Which part of the system would this task primarily affect?
      options:
        - Backend
        - Frontend
        - Generation Engine
        - Microservice
        - Infrastructure
        - Repository
        - Database
        - Authentication
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: A clear and concise description of the task and why it's necessary.
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: A list of criteria that must be met for this task to be considered complete.
      value: |
        - [ ]